AWSTemplateFormatVersion: '2010-09-09'

Transform:
  - AWS::LanguageExtensions

Description: >
  Creates deployment-state SSM parameters for SparrowX services.

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name used for resource naming and tagging.
    AllowedValues:
      - dev
      - prod

  ProjectName:
    Type: String
    Default: sparrowx

  Services:
    Type: CommaDelimitedList
    Description: List of SparrowX service names

Conditions:
  IsDev: !Equals [!Ref EnvironmentName, dev]

Resources:

  # ============================================================
  # Last Successfully Deployed Image To An Environment Dev/Prod
  # ============================================================

  'Fn::ForEach::DeployedParameters':
    - Service
    - !Ref Services
    - '${Service}DevDeployedImage':
        Type: AWS::SSM::Parameter
        Properties:
          Name: !Sub '/${ProjectName}/services/${Service}/${EnvironmentName}/deployed'
          Type: String
          Value: '{}'
          Description: !Sub 'Last successfully deployed image for ${Service} in ${EnvironmentName}'

  # ============================================================
  # PROD - Candidate Image
  # ============================================================

  'Fn::ForEach::ProdCandidateParameters':
    - Service
    - !Ref Services
    - '${Service}ProdCandidateImage':
        Type: AWS::SSM::Parameter
        Condition: IsDev
        Properties:
          Name: !Sub '/${ProjectName}/services/${Service}/prod/candidate'
          Type: String
          Value: '{}'
          Description: !Sub 'Current promotion candidate image for ${Service} in PROD'